[mypy]
python_version = 3.13
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_defs = False
ignore_missing_imports = True
exclude = ^(dist|build|\.venv|tests)/

[mypy-math_engine.plugins.calculus.*]
ignore_errors = False

[mypy-api.*]
ignore_errors = False
