/**
 * Global state management for the Calculus Animator.
 */
export const state = {
    mathField: null,
    allFormulas: [],
    currentSteps: [],
    stepIdx: -1,
    animPlaying: false,
    animTimer: null,
    zoom: 1,
    graphData: null,
    solveResult: null,
    demoMap: {},
    learningLibrary: { categories: [], symbols: [], formulas: [], topics: [] },
    learningTopicById: {},
    learningFormulaById: {},
    learningSymbolById: {},
    learningActiveCategory: "all",
    learningActiveView: "concepts",
    learningSelectedTopicId: "",
    learningSelectedFormulaId: "",
    learningSelectedSymbolId: "",
    learningMode: "home",
    curriculum: { pathways: [] },
    glossary: { terms: [] },
    glossaryById: {},
    glossaryLexicon: [],
    selectedPathwayId: "",
    selectedChapterId: "",
    selectedSlideIndex: 0,
    learningProgress: {},
    relatedTopicPicks: [],
    stepRenderToken: 0,
    baseLatex: "",
    transitionBusy: false,
    queuedDirection: 0,
    currentAnimCopyText: "",
    learningSlideRenderToken: 0,
    pathwaySidebarCollapsed: false,
    solverSidebarCollapsed: false,
    showSlideTextDetails: false,
    slideNotesOpen: false,
    slideNotesWidth: 420,
    showPathwayPicker: false,
    quickSymbolGroups: {},
    activeQuickSymbolTab: "Calculus",
    capacityState: {
        pageIndex: 0,
        totalPages: 0,
        allPagesText: [],
        pageText: "",
        withImage: false,
        text: "",
        lastStats: null,
    },
    badgeTimer: null,
    descTimer: null,
    
    // Constants
    AUTO_STEP_MS: 4000,
    GLYPH_ONLY_MS: 1500,
    POST_REVEAL_MS: 450,
    TRANSITION_MS: 1500 + 450, // GLYPH_ONLY_MS + POST_REVEAL_MS

    // Canvases
    gCanvas: null,
    gCtx: null,
    aCanvas: null,
    aCtx: null,
};
