"""Theme definitions and registration for slide_renderer."""

from typing import Any


THEMES: dict[str, dict[str, Any]] = {
    "modern_dark": {
        "bg_gradient": ("#1a1a2e", "#16213e"),
        "accent": "#e94560",
        "accent2": "#0f3460",
        "title_color": "#ffffff",
        "subtitle_color": "#a0a0c0",
        "body_color": "#d0d0e0",
        "muted_color": "#606080",
        "card_bg": (30, 30, 55, 220),
        "card_border": (233, 69, 96, 80),
        "code_bg": (15, 15, 30, 240),
        "code_color": "#80ffaa",
        "shadow_color": (0, 0, 0, 60),
        "bullet_color": "#e94560",
        "link_color": "#4fc3f7",
        "slide_number_color": "#606080",
        "fonts": {
            "title": {"name": None, "size_ratio": 0.065, "bold": True},
            "subtitle": {"name": None, "size_ratio": 0.035, "bold": False},
            "heading": {"name": None, "size_ratio": 0.045, "bold": True},
            "subheading": {"name": None, "size_ratio": 0.032, "bold": True},
            "body": {"name": None, "size_ratio": 0.028, "bold": False},
            "caption": {"name": None, "size_ratio": 0.022, "bold": False},
            "code": {"name": None, "size_ratio": 0.024, "bold": False, "monospace": True},
            "label": {"name": None, "size_ratio": 0.020, "bold": True},
        },
    },
    "modern_light": {
        "bg_gradient": ("#f5f7fa", "#e4e9f2"),
        "accent": "#4361ee",
        "accent2": "#3a0ca3",
        "title_color": "#1a1a2e",
        "subtitle_color": "#555580",
        "body_color": "#2d2d44",
        "muted_color": "#8888aa",
        "card_bg": (255, 255, 255, 230),
        "card_border": (67, 97, 238, 60),
        "code_bg": (240, 240, 250, 240),
        "code_color": "#d63384",
        "shadow_color": (0, 0, 40, 35),
        "bullet_color": "#4361ee",
        "link_color": "#0077b6",
        "slide_number_color": "#8888aa",
        "fonts": {
            "title": {"name": None, "size_ratio": 0.065, "bold": True},
            "subtitle": {"name": None, "size_ratio": 0.035, "bold": False},
            "heading": {"name": None, "size_ratio": 0.045, "bold": True},
            "subheading": {"name": None, "size_ratio": 0.032, "bold": True},
            "body": {"name": None, "size_ratio": 0.028, "bold": False},
            "caption": {"name": None, "size_ratio": 0.022, "bold": False},
            "code": {"name": None, "size_ratio": 0.024, "bold": False, "monospace": True},
            "label": {"name": None, "size_ratio": 0.020, "bold": True},
        },
    },
    "gradient_ocean": {
        "bg_gradient": ("#0f0c29", "#302b63", "#24243e"),
        "accent": "#00d2ff",
        "accent2": "#7b2ff7",
        "title_color": "#ffffff",
        "subtitle_color": "#a0c4ff",
        "body_color": "#d0e0ff",
        "muted_color": "#5566aa",
        "card_bg": (20, 20, 60, 200),
        "card_border": (0, 210, 255, 60),
        "code_bg": (10, 10, 40, 240),
        "code_color": "#00ffa0",
        "shadow_color": (0, 0, 0, 50),
        "bullet_color": "#00d2ff",
        "link_color": "#00d2ff",
        "slide_number_color": "#5566aa",
        "fonts": {
            "title": {"name": None, "size_ratio": 0.065, "bold": True},
            "subtitle": {"name": None, "size_ratio": 0.035, "bold": False},
            "heading": {"name": None, "size_ratio": 0.045, "bold": True},
            "subheading": {"name": None, "size_ratio": 0.032, "bold": True},
            "body": {"name": None, "size_ratio": 0.028, "bold": False},
            "caption": {"name": None, "size_ratio": 0.022, "bold": False},
            "code": {"name": None, "size_ratio": 0.024, "bold": False, "monospace": True},
            "label": {"name": None, "size_ratio": 0.020, "bold": True},
        },
    },
    "warm_sunset": {
        "bg_gradient": ("#2d1b36", "#6b2737"),
        "accent": "#ff6b6b",
        "accent2": "#ffa07a",
        "title_color": "#ffffff",
        "subtitle_color": "#ffb4a2",
        "body_color": "#f0d0c0",
        "muted_color": "#886666",
        "card_bg": (50, 25, 40, 210),
        "card_border": (255, 107, 107, 60),
        "code_bg": (30, 15, 25, 240),
        "code_color": "#ffd166",
        "shadow_color": (0, 0, 0, 50),
        "bullet_color": "#ff6b6b",
        "link_color": "#ffa07a",
        "slide_number_color": "#886666",
        "fonts": {
            "title": {"name": None, "size_ratio": 0.065, "bold": True},
            "subtitle": {"name": None, "size_ratio": 0.035, "bold": False},
            "heading": {"name": None, "size_ratio": 0.045, "bold": True},
            "subheading": {"name": None, "size_ratio": 0.032, "bold": True},
            "body": {"name": None, "size_ratio": 0.028, "bold": False},
            "caption": {"name": None, "size_ratio": 0.022, "bold": False},
            "code": {"name": None, "size_ratio": 0.024, "bold": False, "monospace": True},
            "label": {"name": None, "size_ratio": 0.020, "bold": True},
        },
    },
    "corporate": {
        "bg_gradient": ("#ffffff", "#f0f2f5"),
        "accent": "#0066cc",
        "accent2": "#003d7a",
        "title_color": "#1a1a1a",
        "subtitle_color": "#4a4a6a",
        "body_color": "#333344",
        "muted_color": "#999999",
        "card_bg": (255, 255, 255, 240),
        "card_border": (0, 102, 204, 50),
        "code_bg": (245, 245, 250, 245),
        "code_color": "#c7254e",
        "shadow_color": (0, 0, 50, 25),
        "bullet_color": "#0066cc",
        "link_color": "#0066cc",
        "slide_number_color": "#999999",
        "fonts": {
            "title": {"name": None, "size_ratio": 0.060, "bold": True},
            "subtitle": {"name": None, "size_ratio": 0.032, "bold": False},
            "heading": {"name": None, "size_ratio": 0.042, "bold": True},
            "subheading": {"name": None, "size_ratio": 0.030, "bold": True},
            "body": {"name": None, "size_ratio": 0.026, "bold": False},
            "caption": {"name": None, "size_ratio": 0.020, "bold": False},
            "code": {"name": None, "size_ratio": 0.022, "bold": False, "monospace": True},
            "label": {"name": None, "size_ratio": 0.018, "bold": True},
        },
    },
}

def register_theme(name: str, theme_dict: dict):
    """Register a custom theme for use with SlideEngine."""
    THEMES[name] = theme_dict
